### ISSUE TITLE
Invalid Function or Declaration [Easy Fix]

### ISSUE THREAD

**Issue by seanny** [Sunehildeep/OnPlayerQuickTurn#1]
I found a spelling mistake in the code that causes an "Invalid Function or Declaration" error on line 22

Here is the buggy code:
```
#if defined OnPlayerQuickTurn
forwrd OnPlayerQuickTurn(playerid, turntype);
#endif  
```

Here is the fix:
```
#if defined OnPlayerQuickTurn
forward OnPlayerQuickTurn(playerid, turntype);
#endif
```

**Comment by Sunehildeep** [comment]
Ah thanks for that.
Didn't acutally see it.

**Comment by seanny** [comment]
I'll go ahead and close this now then. 👍
